namespace: ansible
name: tower
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.unix: '>=1.0'
repository: git@github.com:ansible-collection-migration/ansible.tower.git
documentation: https://github.com/ansible-collection-migration/ansible.tower/tree/master/docs
homepage: https://github.com/ansible-collection-migration/ansible.tower
issues: https://github.com/ansible-collection-migration/ansible.tower/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
